### ISSUE TITLE
Dropped nodes lose itree.icon, become undraggable

### ISSUE THREAD

**Issue by KeithScheiwiller** [helion3/inspire-tree-dom#6] opened 2017-10-27 21:40 UTC
Steps to reproduce:
1) Create a tree with a leaf node that has a custom `itree.icon` set
2) Move node via drag and drop to another location in the tree

Expected behavior:
- Node keeps same icon as defined in its itree
- Node can be dragged again to another location

Actual behavior:
- Node loses icon, reverts to empty-file icon (`itree.icon` becomes undefined)
- Node can no longer be dragged. Other nodes still drag and drop as expected.

**Comment by viveleroi** [comment] 2017-10-27 22:54
The icon issue is partly due to how nodes are exported, which I will change. A secondary improvement is to *not export* the node to begin with *if* it was dragged within the same tree. 

I can't reproduce the second issue, of being unable to drag the node again. Are you able to reproduce this on the live demo? http://www.inspire-tree.com/demos/drag-and-drop.html

**Comment by KeithScheiwiller** [comment] 2017-10-30 13:51
Great, thanks!

You're right, I can't reproduce the second issue on the live demo, only locally. I figured they were related, but since you already knew about the first part it's more likely something I'm doing. You can feel free to close this one out, I'll comment either way if I discover what is causing it.

**Comment by viveleroi** [comment] 2017-10-30 19:25
The icon issue will be fixed with the next inspire-tree release.

I reverted separate work I did here because I didn't pay attention to how nodes were moved, given how I currently handle nodes from any source the same way, they have to be removed the same way. I can revisit this if ever needed but I'll have to split logic into "same-tree" and "different-tree" moves.

**Closed by viveleroi** 2017-10-30 19:25 UTC
