### ISSUE TITLE
Editable and Drag and Drop do not work together

### ISSUE THREAD

**Issue by jeffaotal** [helion3/inspire-tree-dom#22] opened 2018-06-17 02:48 UTC
With the tree configured as:

```
		var tree = new InspireTree({
			editable: true,
		    data: /*[[${treeNodes}]]*/
		});

		tree.nodes().expandDeep();	
	
		new InspireTreeDOM(tree, {
		    target: "#tree",
		    dragAndDrop: true
		});
```

And then trying to drag and drop a node results in:

```
Uncaught TypeError: Cannot set property '$UPD' of null
    at patchComponent (inspire-tree-dom.js:1586)
    at patch (inspire-tree-dom.js:1352)
    at patchKeyedChildren (inspire-tree-dom.js:1685)
    at patchChildren (inspire-tree-dom.js:1489)
    at patchElement (inspire-tree-dom.js:1425)
    at patch (inspire-tree-dom.js:1349)
    at updateClassComponent (inspire-tree-dom.js:1562)
    at patchComponent (inspire-tree-dom.js:1587)
    at patch (inspire-tree-dom.js:1352)
    at updateClassComponent (inspire-tree-dom.js:1562)
```

**Comment by jeffaotal** [comment] 2018-06-17 03:18
This is happening on Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Ubuntu 16.04

**Comment by viveleroi** [comment] 2018-06-18 22:38
Duplicate of #18.

**Closed by viveleroi** 2018-06-18 22:38 UTC
